version: '3'

services:
  robot-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/results
    # By default, runs all tests
    # Examples of running specific tests:
    # Run a specific test folder:
    # command: "/tests/T01"
    # Run a specific test by name:
    # command: ["/tests", "T01_01 Passing Test - Verify String Match"]
